### ISSUE TITLE
Don't let players change colors

### ISSUE THREAD

**Issue by wingzero54** [CivMC/NameColors#6]
We want donors to have a specific color assignment, not the ability to change their color to anything. We should go back to admins assigning a player a namecolor (the commands were all stripped out when adding to /config)

**Comment by Diet-Cola** [comment]
Do we no longer need this considering admins now have prefixes?

**Comment by wingzero54** [comment]
Not strictly necessary now that we have TAB referencing Luckperms roles to give Admins a prefix, but that is not a fix just a coincidental situation alleviating this issue. 

This should probably be converted to an issue for refactoring NameColor to re-add features which were removed in the conversion to /config, or otherwise adding in commands to give admins more control over what NameColor does
